float:
  angular:
  - base_args: ['@metric']
    constructor: ZeelinUSearch
    disabled: false
    docker_tag: ann-benchmarks-zeelin_usearch
    module: ann_benchmarks.algorithms.zeelin_usearch
    name: zeelin-usearch
    run_groups:
      hnsw-32:
        arg_groups:
        - connectivity: [32]
          expansion_add: [200]
          dtype: [f16]
        query_args: [[80, 120, 200, 300, 400, 600, 800]]
      hnsw-48:
        arg_groups:
        - connectivity: [48]
          expansion_add: [300]
          dtype: [f16]
        query_args: [[80, 120, 200, 300, 400, 600, 800]]
      hnsw-64:
        arg_groups:
        - connectivity: [64]
          expansion_add: [400]
          dtype: [f16]
        query_args: [[80, 120, 200, 300, 400, 600, 800]]
